install:
  - cinst pester
  - git clone https://github.com/psake/psake

build: false

test_script:
  - ps: |
        Import-Module .\psake
        Invoke-PSake AppveyorTest
        # this is a hack, psake doesn't propagete exit code
        if ($psake.build_success -eq $false) { 
            exit 1 
        }

on_finish:
    - ps: |
        $stagingDirectory = (Resolve-Path .).Path
        $zipFile = Join-Path $stagingDirectory "$(Split-Path $pwd -Leaf).zip"
        Add-Type -assemblyname System.IO.Compression.FileSystem
        [System.IO.Compression.ZipFile]::CreateFromDirectory((Join-Path $pwd 'ZLocation'), $zipFile)
        @(
            # You can add other artifacts here
            (ls $zipFile)
        ) | % { Push-AppveyorArtifact $_.FullName }
