install:
  - cinst pester
  - git clone https://github.com/psake/psake

build: false

test_script:
  - ps: |
        Import-Module .\psake
        Invoke-PSake AppveyorTest
        # this is a hack, psake doesn't propagete exit code
        if ($psake.build_success -eq $false) { 
            exit 1 
        } else { 
            exit 0 
        }
